### ISSUE TITLE
Type check disallows passing None for option type

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1157]
I might be incorrect here, but when going with 

```
    entrypoint balances(value : option(int)) : bool = 
        switch(value)
            Some(int) => true
```

I can't seem to find a way of passing a `None` here, the SDK explicitly asks me to put a number. The ACI marks the option as such though.

**Comment by davidyuk** [comment]
Well, it works but you have to explicitly pass `undefined` instead of `None`: https://github.com/aeternity/aepp-sdk-js/blob/ddbce389bc44f9a397c9734fd61b6e4e64168bfb/src/contract/aci/transformation.js#L193

```js
const { Universal: Sdk, Node, MemoryAccount } = require('../../dist/aepp-sdk')

const CONTRACT_CODE = `
contract Test =
  entrypoint test(value : option(int)) : bool =
    switch(value)
      Some(int) => true
      None => false
`
const ACCOUNT_KEYPAIR = {
  publicKey: 'ak_2dATVcZ9KJU5a8hdsVtTv21pYiGWiPbmVcU1Pz72FFqpk9pSRR',
  secretKey: 'bf66e1c256931870908a649572ed0257876bb84e3cdf71efb12f56c7335fad54d5cf08400e988222f26eb4b02c8f89077457467211a6e6d955edb70749c6a33b'
}
const NODE_URL = 'https://testnet.aeternity.io'
const account = MemoryAccount({ keypair: ACCOUNT_KEYPAIR });

(async () => {
  const node = await Node({ url: NODE_URL })
  const sdk = await Sdk({
    nodes: [{ name: 'testnet', instance: node }],
    compilerUrl: 'https://compiler.aepps.com',
    accounts: [account]
  })

  const contract = await sdk.getContractInstance(CONTRACT_CODE)
  await contract.deploy([])
  let callResult
  callResult = await contract.methods.test(undefined)
  console.log('result', callResult.decodedResult)
  callResult = await contract.methods.test(9)
  console.log('result', callResult.decodedResult)
})()
```

```bash
$ node contract.js
result false
result true
```

**Comment by nikita-fuchs** [comment]
Hmm, damn.. `undefined` is tricky to handle in today's web frameworks. Can I make a proposal please: As the sophia syntax knows `None`, could we allow `"none"` and `"None"` plus  `"undefined"` and `"null"` to be passed as strings, please ? Somewhere after the hardfork is through ?

**Comment by nikita-fuchs** [comment]
Two important arguments here copy-pasted from a discussion I had on this topic in discord: 

1. Why I'm vouching for that pragmatic solution instead of sticking to the "purely technically correct one" leaving `undefined` is that I can see all these posts coming up like: "I built a handful of contracts in aeternity now but when calling a function my my new one it returns undefined" - it's just a keyword that brings up confusion in people in the JS space.

2. as sophia was always about safety, nothing is ever implicitly something else if these two things are not 1:1 identical. basically the whole idea about strict typing. We subvert that strategy on JS level when making undefined an allowed token:
```
myInput = 4

someContract.myMethod(myinput)
```
whoops, passed undefined when I wanted to pass 4.

**Comment by davidyuk** [comment]
After this issue was created, we have switched to calldata package, which manages smart contract arguments handling. It is too expensive to have custom handling on sdk side (because of nested structures). So, if this issue is still actual it should be forwarded to calldata.

Personally, I'm not a fan of accepting undefined as string because for example it significantly complicates form validation: we have a smart contract function that accepts `option(string)`, but we want to ensure that string is provided then we have to validate user input against `'undefined', 'null', 'none', 'None', ''` instead of just empty string.

> `undefined` is tricky to handle in today's web frameworks

I'm not sure about this. The last time we chose to use `undefined` as the lack of value to be compatible with TypeScript. Alternatively, you can use `null` or `{ None: [] }` (as variant type in Sophia).
