### ISSUE TITLE
v8.0.0-beta.1: Error when calling static functions

### ISSUE THREAD

**Issue by marc0olo** [aeternity/aepp-sdk-js#1178]
While updating aeproject I faced an issue and created a separate repo to verify it. The error looks like this:
```
/home/marc0olo/git/aeternity/aepp-sdk-js-test/node_modules/swagger-client/lib/http.js:98
    const error = new Error(res.statusText);
                  ^

Error: Not Found
    at http (/home/marc0olo/git/aeternity/aepp-sdk-js-test/node_modules/swagger-client/lib/http.js:98:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5) {
  status: 404,
  statusCode: 404,
  responseError: {
    name: 'SyntaxError',
    message: "Unexpected 'o'",
    at: 2,
    text: '[object Blob]'
  }
}
```

You can check out the following repo to reproduce:
- https://github.com/marc0olo/aepp-sdk-js-test

-> The repo also contains a docker-compose file to start the required stack.

**Comment by marc0olo** [comment]
cc @davidyuk @mradkov 

not sure whether this is the same error that @thepiwo faced. I guess it's another issue

**Comment by davidyuk** [comment]
This is nginx/swagger configuration issue. The sdk requests `http://localhost:3001/v3/debug/transactions/dry-run` instead of `http://localhost:3001/internal/v3/debug/transactions/dry-run` even if `internalUrl` is `http://localhost:3001/internal`.

The specification at http://localhost:3001/internal/api?oas3 contains:
```
  "servers": [
    {
      "url": "/v3"
    }
  ],
```
to have it working it should be `/internal/v3`. Also, currently sdk fetches spec file once and uses it for both external and internal api that is not correct I think.

As a workaround, sdk can try to modify spec file on the fly, but this seems to be a fragile approach. This is doable if I split base swagger support (for compiler and middleware) and a workarounds for node (I already have a set of them).

**Comment by marc0olo** [comment]
thanks @davidyuk, I modified the nginx proxy config in the docker setup in my example and got it working now.

anyway, we should make the internalUrl configurable or find a solution to the problem you mentioned.

**Comment by davidyuk** [comment]
SDK@8.1.0 uses the external dry-run endpoint, so internal API is not needed for most use cases (#1217).

Also, the internal api of the node should have a correct swagger file, I have asked core team to make it configurable in the corresponding issue.
