### ISSUE TITLE
Making a call (Non state change calls) costs AE

### ISSUE THREAD

**Issue by genievot** [aeternity/aepp-sdk-js#1231]
https://github.com/aeternity/fire-editor/issues/58#issue-927095446

**Comment by marc0olo** [comment]
as @nikita-fuchs already explained the SDK provides various ways to perform contract calls. though it makes sense to use `dry-run` functionality for non-stateful entrypoints you can still broadcast and get the tx mined and this - of course - costs you a small fee.

it depends on how the method is being called. I guess the improved documentation (#1220) that I currently work on will make that more clear.

when I remember correctly you marked the entrypoint that you are talking about as `stateful` which means that the SDK doesn't perform a `dry-run` but signs and broadcasts the tx instead.

sneak peak of the updated docs:

## 5. Call contract entrypoints

### a) Stateful entrypoints 
According to the example above you can call the `stateful` entrypoint `increment` by using one of the following lines:

```js
const tx = await contractInstance.methods.increment(3) // recommended
// or
const tx = await contractInstance.methods.increment.send(3)
// or
const tx = await contractInstance.call('increment', [3])
```

Note:

- The functions `send` and `call` provide an explicit way to tell the SDK to sign and broadcast the transaction.
- When using the `increment` function directly the SDK will automatically determine if it's a `stateful` entrypoint.

### b) Regular entrypoints
The aeternity node can expose an API endpoint that allows to execute a `dry-run` for a transaction. You can make use of that functionality to get the result of entrypoints that don't execute state changes. Following lines show how you can do that using the SDK for the `get_count` entrypoint of the example above:

```js
const tx = await contractInstance.methods.get_count() // recommended
// or
const tx = await contractInstance.methods.get_count.get()
// or
const tx = await contractInstance.callStatic('get_count', [])

// access the decoded result returned by the execution of the entrypoint
console.log(tx.decodedResult);
```

### c) Payable entrypoints
You will probably also write functions that require an amount of `aettos` to be provided. These functions must be declared with `payable` and (most likely) `stateful`. Let's assume you have declared following Sophia entrypoint which checks if a required amount of `aettos` has been provided before it continues execution:

```sophia
payable stateful entrypoint fund_project(project_id: int) =
        require(Call.value >= 50, "at least 50 aettos need to be provided")
        // further logic ...
```

In order to successfully call the `fund_project` entrypoint you need to provide at least 50 `aettos`. You can do this by providing the desired amount of `aettos` using one of the following lines:

```js
const tx = await contractInstance.methods.fund_project(1, { amount: 50 }) // recommended
// or
const tx = await contractInstance.methods.fund_project.send(1, { amount: 50 })
// or
const tx = await contractInstance.call('fund_project', [1], { amount: 50 })
```

**Comment by genievot** [comment]
Thanks @marc0olo , This is something definitely requires an explanation in docs.
