### ISSUE TITLE
SDK Compiler setting error (v8.2.1)

### ISSUE THREAD

**Issue by sunbx** [aeternity/aepp-sdk-js#1236]
I updated the new version of the SDK and found that the 8.2.0 call contract failure problem was resolved, but when I set the compiler address myself, I found that the request and the set address were not the same
![image](https://user-images.githubusercontent.com/8652427/123035790-89be7580-d41e-11eb-9986-0bc2c2e9160b.png)

I use sdk set is https://compiler.aeasy.io/
The last request is http://compiler.aeasy.io/

**Comment by marc0olo** [comment]
Hi @sunbx,

the actual problem is sitting in the deployment configuration of the http compiler where `https` isn't defined under schemes. The respective issue is here: https://github.com/aeternity/aesophia_http/issues/70.

So currently the SDK has a temporary workaround for the hosted services. If you are hosting yourself you need to either fix that or wait until the issue above is solved and a new release is published.

@davidyuk @mradkov correct me if I said anything wrong 😅

**Comment by sunbx** [comment]
This should be fixed. Box AEPP is a small service hosted on the client side and the compiler address can be set. So look for a fix in the next version?

**Comment by davidyuk** [comment]
As I know, the compiler doesn't support HTTPS by itself, so it is more deployment issue. Have you setup by yourself a reverse proxy that makes the compiler work through HTTPS? If so please update your configuration with a custom swagger file (copy of default swagger file + `"schemes": ["https"]`), after that sdk should become compatible with your deployment. In Nginx the configuration may be like:

```nginx
server {
  location /api {
    root /<path to filder with custom swagger file>/;
  }

  location / {
    proxy_pass http://<compiler>:3080;
  }
}
```

This issue is not on the SDK side, so I'm proposing to close this issue.

**Comment by sunbx** [comment]
The problem should be that the compiler address set is not the same as the final access compiler address, and the server configuration agent is not affected. At the very least, you should ensure that the SDK sets the address and ultimately accesses the address.。

It's not set :  https://compiler.aeasy.io
The last thing to visit is http://compiler.aeasy.io

The SDK internally automatically converts HTTPS to HTTP is wrong

Or give a hint?

**Comment by davidyuk** [comment]
Compiler Swagger doesn't contain `schemes`, so this issue should be fixed
