### ISSUE TITLE
node-pool checker fails on node provided in sdk.pool.get

### ISSUE THREAD

**Issue by etharner** [aeternity/aepp-sdk-js#1261]
Introduced here: https://github.com/aeternity/aepp-sdk-js/blob/99f26eb5030b5aa170316653635d5fa1eb10ee95/src/node-pool/index.js#L144-L153

sdk.pool.get method returns object which fails JOI check in code above, thus leading to:
![image](https://user-images.githubusercontent.com/7098449/127113167-a397e386-e3e3-43c6-85cd-0c3ba38a5ba0.png)

Looks like when adding new node structure unsupported by JOI check created: https://github.com/aeternity/aepp-sdk-js/blob/99f26eb5030b5aa170316653635d5fa1eb10ee95/src/node-pool/index.js#L62-L70

**Comment by davidyuk** [comment]
I've reproduced this error on 8.2.1 using code:
```js
  const sdk = await Universal({
    address: 'ak_asd',
    nodes: [{ name: 'test', instance: await Node({ url: 'https://testnet.aeternity.io' }) }],
  })
  const nodeFromPool = sdk.pool.get('test')
  const sdk2 = await Universal({
    address: 'ak_asd',
    nodes: [nodeFromPool],
  })
  console.log(await sdk2.api.getStatus())
```
switching to 10.0.0 I don't see this error, because we have dropped JOI in b00d98419e4b2718fd9fcd31bb338daaed3acb06 and I wrote this check manually not checking the lack of extra fields
https://github.com/aeternity/aepp-sdk-js/blob/72907f351579444ebd269668f254d4956657e38b/src/node-pool/index.js#L146-L164
