### ISSUE TITLE
nameFee is requested in calculateMinFee function

### ISSUE THREAD

**Issue by etharner** [aeternity/aepp-sdk-js#1266]
In wallet we were using v1 of `nameClaim` schema and after updating to 0.8.2 sdk v1 has been removed, so we switched to v2. We are using that schema to calculate min fee through `calculateMinFee` function. It appeared that calling of this function with `vsn: 2` led to this error in sdk:
![image](https://user-images.githubusercontent.com/7098449/131338551-84649757-98e1-4e10-a509-721bd4703f75.png)

After some research I've found that this `formatAmount` is calling with `nameFee: undefined` because we are not passing this parameter to function.
Is this a bug or we really should provide some default `nameFee` (which sdk actually has in `import { getMinimumNameFee } from '@aeternity/aepp-sdk/es/tx/builder/helpers';`) for the function which is calculating the fee?

**Comment by marc0olo** [comment]
@mradkov is this related to https://github.com/aeternity/aepp-sdk-js/issues/1252 ? not sure if I understood the error here correctly

**Comment by mradkov** [comment]
Let me check

**Comment by etharner** [comment]
This is happening because:
1) `nameFee` is presented in `nameClaimTx` schema https://github.com/aeternity/aepp-sdk-js/blob/5f1cb1105eff0393b4cd45c96a88202698013ec1/src/tx/builder/schema.js#L482-L491
2) while calling of `calculateMinFee` this call chain is happening: `calculateMinFee -> buildFee -> buildTx -> buildRawTx -> transformParams` and in last function sdk is getting the schema and call `formatAmount` for `amount` fields in schema.

`nameClaimTx` has `nameFee` field with `amount` type, so if we don't pass it it will try to `formatAmount (undefined)` which will lead to error in op post.

So my question is: do we need `nameFee` in this schema or should we process schema differently for calculating the fee?

**Comment by marc0olo** [comment]
@mradkov do you currently have time for this stuff or should @subhod-i have a look?

**Comment by subhod-i** [comment]
@etharner 
With the current release version, schema expects the nameFee field. The error message is maybe not appropriate. Could you please share the working version of this? Also, are you able to fix this and the requirements fulfilled?

**Comment by marc0olo** [comment]
@etharner I am generally very confused about this questions regarding different schemas. are you really sure that you explicitely used v1? because I really doubt that. the default has been v2 for a very long time IMO and I am not even sure if v1 would have worked. I doubt it.

the commit where the old schemas have been dropped/removed is this one:
- https://github.com/aeternity/aepp-sdk-js/commit/f18d305ca29204f006a438c157add0b511df4e93#diff-ad38e160e81f081497c7c5146c2f092580b6e1fb9989415eae179c477dfbfb84

I don't really understand the problem. can you please elaborate a bit more detail what's now different compared to the previous version of the SDK from the "usage perspective"?

are you saying that before this change the call of `nameClaim` automatically calculated the required fee and now it isn't doing this anymore?

**Comment by marc0olo** [comment]
the thing here is that I am pretty sure that I tested the calculation for the `nameFee` when updating the documentation recently. so I am not sure if there is really sth. wrong here or what's generally the problem:
- https://aeternity.com/aepp-sdk-js/latest/guides/aens.html#claim

**Comment by marc0olo** [comment]
@etharner are you talking about the initial nameFee for claiming a name or for a claim during an auction?

there is also `computeBidFee` to be used during an auction and here it obviously makes sense to provide the current bid as this needs to be incremented accordingly:
- https://github.com/aeternity/aepp-sdk-js/blob/b0454fb3695f1ef755f0c92843b6bf1c75a31633/src/tx/builder/helpers.js#L304
- https://aeternity.com/aepp-sdk-js/develop/guides/aens.html#bid-during-an-auction

**Comment by marc0olo** [comment]
need to wait for feedback here.

**Comment by marc0olo** [comment]
> I'm talking about initial nameFee for claiming a name

so your expectation here would be as follows:

**Given**
no fee provided

**Do (automatically)**
calculateNameClaimFee

right?

---------

Then we come back to the initial topic here:
- is this already being executed by the SDK? (seems like according to the error log)
- why is the error happening (because it used to work like this in the past?)

**Comment by marc0olo** [comment]
@subhod-i @davidyuk can we close this or do you think we need to to sth. here? was quite unproductive discussion IMO
