### ISSUE TITLE
Add deployment params to _contract.deployInfo

### ISSUE THREAD

**Issue by nikita-fuchs** [aeternity/aepp-sdk-js#1350]
Currently, we put lots of deployment TX info on the contract object. It would be useful for eventual later contract verification and generally a better overview, if the deployment params could also be found there. Not highest prio of course,  but it would be a really nice addition to the extensie amount of info the SDK already provides.

![image](https://user-images.githubusercontent.com/11761828/144608327-ed64fc0c-9fd1-4605-b525-0fcf6a58f6dc.png)

**Comment by davidyuk** [comment]
I'm for making arguments easily accessible by contract address rather than storing them in contract instance. Also, if you deployed a contract then just remember arguments if you need them.

Arguments for dropping `contract.deployInfo` in general:
- storing it in a contract instance opens a class of errors when somebody referenced it in the already deployed contract (or reduces performance if we would request deploy info for deployed contracts)
- if the user needs to handle deploy info he can access it as the result of the `deploy` function
- dropping data not needed for a contract instance would make SDK code easier to read
- the reduction of exposed apis makes it easier to refactor stuff without making breaking changes

**Comment by davidyuk** [comment]
I'm still for keeping SDK api as simple as possible. Currently, the only artifact that is persisted after deploying is a contract address because it is needed for subsequent calls:
https://github.com/aeternity/aepp-sdk-js/blob/370f1e30064ad0239ba59931908d9aba0a2e86b6/src/contract/Contract.ts#L307-L314
The rest is returned as `$deploy` result.
