### ISSUE TITLE
Be able to distinguish swagger errors

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#1352]
fix issues in https://github.com/swagger-api/swagger-js/pull/2094

related to #1194

**Comment by marc0olo** [comment]
> fix issues in [swagger-api/swagger-js#2094](https://github.com/swagger-api/swagger-js/pull/2094)

what about revisiting that old PR? I mean only if they are interested in it 😅

**Comment by subhod-i** [comment]
Swagger client-generated errors can be wrapped in a custom Error class. 
Writing different Error classes based on the body of the HTTP response is may not be a good idea since the core and JS SDK team agree on pre-defined error sets. The closed PR makes sense now https://github.com/swagger-api/swagger-js/pull/2094. In fact, we can use the  swagger client response interceptor to write such classes at https://github.com/aeternity/aepp-sdk-js/blob/72907f351579444ebd269668f254d4956657e38b/src/utils/swagger.js#L68

**Comment by davidyuk** [comment]
The issue is still actual, but I planning to fix it by dropping swagger-client while doing #1216.

> Writing different Error classes based on the body of the HTTP response

I'm not proposing it either, just to have a special class like `FetchResponseError` for this case instead of a general `Error`.

> In fact, we can use the swagger client response interceptor to write such classes

Yep with a bit of code duplication, I would still consider to make a contribution to swagger-client repo

**Comment by davidyuk** [comment]
We've switched to autorest and now request errors represented by RestError class from '@azure/core-rest-pipeline' 🎉
