### ISSUE TITLE
Import keys from aepp-python-sdk

### ISSUE THREAD

**Issue by kryztoval** [aeternity/aepp-sdk-js#139]
## Description
Importing a key from aepp-python-sdk which is version 3 does not work with aepp-sdk-js

## Expected Behavior
Keys should be interchangeable to some degree, or cross exportable.
 
## Current Behavior
Currently keys in python are 32bytes and in javascript are 64bytes, also the wallet file is incompatible between versions

## Possible Solution
add support for 32 byte private keys or for v3 wallet files?

## Steps to Reproduce
Get a string of 32bytes and use it as a key in the aecli.js
Copy a wallet from a python-sdk and try using it in the aecli.js

## Environment / Context
Client side

NOTE: this may need to be moved, but since the aecli.js is still part of this package in the version available i wrote it here.

**Comment by kryztoval** [comment]
On the possible solutions, the python aepp-python-sdk allows exporting the 64bytes key with
aecli account address --private-key wallet.file
```
# ./aecli account address --private-key wallet.file
Enter the account password []:
!Warning! this will print your private key on the screen, are you sure? [y/N]: y
<account>
  Address ___________________________________________ ak_hyFiqcX4sqGiNAo9ffmzZBR2hu3WDB6Dmc4yagN36C6yjeqiC
  Signing key _______________________________________ c6f424cfc15d7a97a66961fd2705d599f42fe8689381dd33f57b6328e9db7d8a5d06f39fa978c45a5ac553888c0b4e43783d8a36a67575153f727b2b8b2dab23
</account>
```

Using this signing key in the aepp-sdk-js' aecli.js save will recreate the same account and make a v1 compatible file.

**Comment by marc0olo** [comment]
I am currently working on a java implementation and want to share that I also struggled with that 64 byte private key (hex) until @kryztoval told me that the public key is included in the string.

in my opinion all sdks should work with the same represantation (whether it is 32 bytes or 64 bytes)

**Comment by noandrea** [comment]
Hello, all the sdks use the 64 bytes representation for the private key, that is 
(32b private key + 32b public key).

The underlying implementation of the Ed25519 curve may require 32 or 64 bytes but the sdks should use the 64 bytes representation. 

For example for the python sdk cli we have:

```
$ aecli account create TEST.json # create a new account  
Enter the account password []: 
<account>
  Address ___________________________________________ ak_2faSf9nYZW8jNMG6AfyYPvuvx98QHQYUUhtPz3ufSTJ3xb9iPT
  Path ______________________________________________ /..../TEST.json
</account>
$ aecli account address --private-key TEST.json # print the keys of an account
Enter the account password []: 
!Warning! this will print your private key on the screen, are you sure? [y/N]: y
<account>
  Address ___________________________________________ ak_2faSf9nYZW8jNMG6AfyYPvuvx98QHQYUUhtPz3ufSTJ3xb9iPT
  Signing key _______________________________________ 447ac1f87bc017ac9644112da6c0ca63192e4f9cab43db6b3bc4906082847ba0db49f9d1cdb068dbf91e0f8a21002781f971cdffb06d5e5f9e8b0e71c7e2c692
</account>
```
in this case `447ac1f87bc017ac9644112da6c0ca63192e4f9cab43db6b3bc4906082847ba0db49f9d1cdb068dbf91e0f8a21002781f971cdffb06d5e5f9e8b0e71c7e2c692` is the 64 bytes private key hex encoded.

Programmatically you can obtain the same:
```
$ python
Python 3.6.4 (default, Jan  6 2018, 11:51:59) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from aeternity import signing
>>> account = signing.Account.from_keystore("TEST.json", "") # open the account generated before
>>> account.get_address() 
'ak_2faSf9nYZW8jNMG6AfyYPvuvx98QHQYUUhtPz3ufSTJ3xb9iPT' # this is the base58 encoded with checksum public key (32 bytes)
>>> account.get_private_key()
'447ac1f87bc017ac9644112da6c0ca63192e4f9cab43db6b3bc4906082847ba0db49f9d1cdb068dbf91e0f8a21002781f971cdffb06d5e5f9e8b0e71c7e2c692'
>>> 
```

`'ak_2faSf9nYZW8jNMG6AfyYPvuvx98QHQYUUhtPz3ufSTJ3xb9iPT'` is the base58 encoded with checksum public key (32 bytes + 4 bytes for checkusm), and `447ac1f87bc017ac9644112da6c0ca63192e4f9cab43db6b3bc4906082847ba0db49f9d1cdb068dbf91e0f8a21002781f971cdffb06d5e5f9e8b0e71c7e2c692`is again the private key (64 bytes) hex encoded.


The reason why the public key is encoded in base58 with checksum and with the `ak_` prefix and the private key is a hex encoded string is due to the fact that a private key is not an entity that is managed by the node and therefore the specifications do not prescribe an encoding schema.
