### ISSUE TITLE
PayingForTx Guide Outdated

### ISSUE THREAD

**Issue by kenodressel** [aeternity/aepp-sdk-js#1687]
**Describe the bug**

The paying for tx guide seems quite outdated. Links are dead and it does not really cover any detail.

**To Reproduce**
1. Go to https://github.com/aeternity/aepp-sdk-js/blob/develop/docs/guides/paying-for-tx.md
2. Click on any link

**Expected behavior**

Links should lead to the correct places.

**Comment by marc0olo** [comment]
that's a tricky part here because it's a generated markdown file which is not existing in the repo 😅

not sure about the best way to handle it.

here it works: https://docs.aeternity.com/aepp-sdk-js/v12.1.3/guides/paying-for-tx/

**Comment by kenodressel** [comment]
Well at the moment its linked in the README.md file and does not work. So we need to fix it :)

**Comment by davidyuk** [comment]
The most obvious is to store built examples in the  repository, but storing build artifacts in a repo is a bad practice and it won't work if we had a link to API documentation because it is HTML. Also, we can have a redirect to a source file, but this also won't work for API docs. So, I'm proposing to have a direct link to the latest released SDK's docs at docs.aeternity.com in cases like this.
