### ISSUE TITLE
Types discrepancy in transaction parameters(buildTx and unpackTx)

### ISSUE THREAD

**Issue by subhod-i** [aeternity/aepp-sdk-js#1727]
### buildTx
The options object passed to the `buildtTx` method even in the tests resembles the same error. 

```
Argument of type '{ senderId: `ak_${string}`; recipientId: `ak_${string}`; amount: number; payload: string; }' is not assignable to parameter of type 'Omit<Omit<Omit<Partial<Pick<{ payload: string | undefined; }, "payload">> & Omit<{ payload: string | undefined; }, "payload">, "tag" | "VSN"> & { ...; }, "nonce" | ... 3 more ... | "abiVersion"> & { ...; }, "onNode"> & { ...; }'.
  Object literal may only specify known properties, and 'senderId' does not exist in type 'Omit<Omit<Omit<Partial<Pick<{ payload: string | undefined; }, "payload">> & Omit<{ payload: string | undefined; }, "payload">, "tag" | "VSN"> & { ...; }, "nonce" | ... 3 more ... | "abiVersion"> & { ...; }, "onNode"> & { ...; }'.ts(2345)
 ```
 Data passed in here is not assignable to the defined types https://github.com/aeternity/aepp-sdk-js/blob/2c992b9cfb056adcb5468b4306fee02a2e2e0063/test/integration/rpc.ts#L291
 
 ### unpackTx
Property 'fee' does not exist on type 'RawTxObject<Partial<Pick<{ payload: string | undefined; }, "payload">> & Omit<{ payload: string | undefined; }, "payload">>'.
 
 ```
 const { fee } = unpackTx(spendTx, Tag.SpendTx).tx;
 ```
 The above code indeed has `fee` data in the return type at runtime but the type checker throws an error at the compile time.
  

 Expected behavior: compatible types as expected.

**Comment by davidyuk** [comment]
Recently I make a set of refactorings to make the result of `unpackTx` acceptable in `buildTx`. It has better handling of different tx schema versions:
https://github.com/aeternity/aepp-sdk-js/blob/36fd8e565bb06f47d783fde4d2df3615ce3490a1/test/unit/tx.ts#L125-L147
https://github.com/aeternity/aepp-sdk-js/blob/36fd8e565bb06f47d783fde4d2df3615ce3490a1/test/unit/tx.ts#L236-L260
Instead of generics, I'm switching to the union of all possible transactions type.

> senderId: aepp.address

I've fixed type checks in tests, so it should work now.

```js
const { fee } = unpackTx('tx_...', Tag.SpendTx);
```

`fee` type is detected correctly now.

If you have any other failure cases, please submit them
