### ISSUE TITLE
Iframe Failed to connect to aepp broadcast

### ISSUE THREAD

**Issue by sunbx** [aeternity/aepp-sdk-js#1826]
If SDK13 is used, Demo integration can obtain the address correctly, but it fails to be broadcast

<img width="1375" alt="image" src="https://github.com/aeternity/aepp-sdk-js/assets/8652427/5ab9ae41-bf68-4d97-a03e-f6291be9f30b">

**Comment by davidyuk** [comment]
Are you updating Superhero dex to sdk@13?

**Comment by sunbx** [comment]
Yes, I used SDK13, Iframe as the wallet, and SuperheroDEX as the test. There was an error during the broadcast

**Comment by davidyuk** [comment]
https://github.com/aeternity/aepp-sdk-js/blob/0dcb239939aa299ffc597215b83c10305a70bafc/examples/browser/wallet-iframe/src/App.vue#L90

I've preroduced it using wallet-iframe from examples and https://aepp.dex.superhero.com/. In fails in a confirmation popup on iframe wallet side because tries to serialize Proxy to JSON. Initially I've [not implemented](https://github.com/aeternity/aepp-sdk-js/blob/0dcb239939aa299ffc597215b83c10305a70bafc/src/AeSdkMethods.ts#L19-L37) Proxy methods that is not needed to sdk, but I disided to do so to simplify debugging and so.

As a workaround you can avoid converting to json (or so) sdk's options `onAccount`, `onNode`, `onCompiler`
https://github.com/aeternity/aepp-sdk-js/pull/1830/files#diff-cfd2a137877dee67360e220542d7876b9ac1a0dabdef8ba09cb2feece773144cR90-R93
