### ISSUE TITLE
Can't tree shake crypto module

### ISSUE THREAD

**Issue by davidyuk** [aeternity/aepp-sdk-js#383]
Importing of `salt` from '@aeternity/aepp-sdk/es/utils/crypto' brings too lot of dependencies:

Before importing:
![crypto-before](https://user-images.githubusercontent.com/9007851/57215581-a0f73a80-6fed-11e9-9af1-442849b69a77.png)
After importing:
![crypto-after-2](https://user-images.githubusercontent.com/9007851/57215590-a5235800-6fed-11e9-9d5b-bc018fbd4de1.png)

These reports generated by https://github.com/davidyuk/vue-reproductions/tree/sdk-promise-cancellation, using `npm run build -- --report`.

It is important that the `salt` function does not depend on any packages at all.

**Comment by noandrea** [comment]
to decrease the size of the bundle we are going to focus on #756 that ha far more impact

**Comment by davidyuk** [comment]
@noandrea will you reopen this when that one will be fixed?

**Comment by noandrea** [comment]
I wasn't plan to, why I would I close it in the first place. 
As far I understand your request is about the bundle size, and we have found out that the joy-browser has much more impact on the size of the bundle and it is way less critical than for example nacl. 

Naturally we cannot just remove the joy-browser dependency since it will cripple the high level contract interaction, so it requires some research to find a better choice.

Also both this and the #756 are considered enhancements not bugs. 

But if you feel that this one is important to you, by all means reopen it and elaborate more on the subject

**Comment by davidyuk** [comment]
`aes-js` is one of the biggest unused dependencies of the Base app, and to remove it from there, I think we need to solve this issue.

> elaborate more on the subject

For me, this issue looks quite obvious. Do you have any specific questions? Have you tried the attached reproduction?
