### ISSUE TITLE
Deployment hangs when using account that is not present

### ISSUE THREAD

**Issue by maptuhec** [aeternity/aepp-sdk-js#459]
When trying to deploy a smart contract with an account that is not present (or have zero amount of AEs) on testnet, the deployment hangs or returns the following error:

## Expected Behavior
It should throw an error that can be caught, and don't leave the application hanging.

## Current Behavior
Error is not thrown, the function **address()** doesn't resolve (in my opinion) the promise correctly and thus leave the script hanging

## Possible Solution
Resolve the promise from calling the **address()** function from the **memory** class, to be able to throw and catch the error
## Steps to Reproduce

1. Try to deploy contract with an account that has zero balance or it is not present on the current network
1.1 You can try using this account 
 `"secretKey":"9262701814da8149615d025377e2a08b5f10a6d33d1acaf2f5e703e87fe19c83569ecc7803d297fde01758f1bdc9e0c2eb666865284dff8fa39edb2267de70db",
"publicKey": "ak_f9bmi44rdvUGKDsTLp3vMCMLMvvqsMQVWyc3XDAYECmCXEbzy"`
2. Wait 

## Environment / Context
This is testnet on localhost node(2.5.0) and on sdk-testnet node.

**Comment by nduchak** [comment]
I try to repro this issue. And that's what i found:
 - When you try to deploy contract using empty/zero account 
` await client.contractDeploy(code.bytecode, identityContract)`
iI get get this error `Error: Giving up after 10 blocks mined. TxHash th_2BXNyij6KVNpkRqL5Zy52CN1QcKFDtW2gN2JTLVahAcvJcStDN`
Which mean that tx can't be mined because of not enough funds.
 - If you want to prevent this you simply can use `verify` option
`await client.contractDeploy(code.bytecode, identityContract, [], { verify: true })`

**Comment by maptuhec** [comment]
Thanks, it works with the `verify` option
