### ISSUE TITLE
Uncaught (in promise) TypeError: Assignment to constant variable. in swagger.js:241

### ISSUE THREAD

**Issue by dadaphl** [aeternity/aepp-sdk-js#74]
This error occurs int the current version of the aepp-blockchain-explorer (https://sdk-testnet-explorer.aepps.com/#/)    `"@aeternity/aepp-sdk": "0.18.0-0.1.1"` current sdk-testnet node is version 0.19
```
swagger.js:241 Uncaught (in promise) TypeError: Assignment to constant variable.
    at s.v (swagger.js:241)
    at memoizeWith.js:39
    at _arity.js:22
    at s.K.s.u (swagger.js:450)
    at t.f (mapObjIndexed.js:28)
    at t.@@transducer/step (_xwrap.js:12)
    at _reduce.js:9
    at I (_reduce.js:43)
    at mapObjIndexed.js:27
    at Object.e (_curry2.js:26)
```

**Comment by ricricucit** [comment]
This is happening because of your exclusion of `node_modules` folder, when transpiling ES6 to ES5 and it's not necessarily to be seen as an "error".

[Here](https://github.com/aeternity/aepp-contracts/blob/feature/new-settings/webpack.config.js#L74) you can see how I've solved this.

@jsnewby this is what I was telling you that we should add to the documentation (for people using ES6 modules directly, to make use of three shaking).

**Comment by ricricucit** [comment]
outdated
