### ISSUE TITLE
Evaluate Fetch API instead of Axios for HTTP requests

### ISSUE THREAD

**Issue by noandrea** [aeternity/aepp-sdk-js#837]
**Is your feature request related to a problem? Please describe.**
Axios is a the facto standard library for async http requests, but modern browser they ship now with the `Fetch` API that can be used in place of Axios

**Describe the solution you'd like**
Evaluate if it is possible to use Fetch API instead of Axios

**Additional context**
Since axios is an extremely popular library, stable and well tested, it is important to identify significant benefits that justify the switch.

**Comment by davidyuk** [comment]
> There was no mainnet, there was no stable release of any of the pieces of the ecosystem and when it was evaluated it presented some issues.

do you think we can't switch to plain fetch without significant breaking changes? I think, the only thing that could break is the ability to pass config to axios.

> Since axios is an extremely popular library, stable and well tested

for obvious reasons, we can't measure the popularity of `fetch` api, but [node-fetch](https://www.npmjs.com/package/node-fetch) package (that should be used in nodejs as a replacement for window.fetch) has about 2 times more downloads than [axios](https://www.npmjs.com/package/axios).

The bundle of empty vue app becomes 15kb bigger if used `axios.get` instead of `fetch`.
https://github.com/davidyuk/vue-reproductions/tree/fetch-axios
https://github.com/davidyuk/vue-reproductions/tree/fetch-plain

**Comment by davidyuk** [comment]
fixed in 0d821614e83623f5aeb04133197e8c16de7818b1
